name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # 4. It should checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 5. It should set up a Node environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can specify your preferred version here

      # 6. It should install all dependencies
      - name: Install dependencies
        run: npm install

      # 7. It should build the app using npm run build
      - name: Build app
        run: npm run build

      # Authenticate to Google Cloud using your Secret
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Set up the gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Build the image with Cloud Build and push to Artifact Registry
      - name: Cloud Build submit
        run: |
          gcloud builds submit --tag "us-central1-docker.pkg.dev/notely-491712/notely-ar-repo/notely-app:latest" .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image "us-central1-docker.pkg.dev/notely-491712/notely-ar-repo/notely-app:latest" \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-491712 \
            --max-instances=4
